### ISSUE TITLE
Script of "robust_nmf_programs.R" is missing in module 2

### ISSUE THREAD

**Issue by helianthuszhu** [gabrielakinker/CCLE_heterogeneity#1]
Hi,
   Thanks for providing the wonderful code used in NG ccle paper. I just noticed that the script robust_nmf_programs.R for module 2 was not in the repository. I would be great if you can check and see it is somewhere. 

Best,
Xiaoqiang

**Comment by gabrielakinker** [comment]
Hi Xiaoqiang,
I am glad you found the code helpful.  You are right, the file was missing. 
I just uploaded it.
Best,
Gabi
