### ISSUE TITLE
Mistype in packages.R

### ISSUE THREAD

**Issue by funpys** [gabrielakinker/CCLE_heterogeneity#2]
Thank you for providing useful package.
I found mistype in packages.R
install.packages(c("NMF", "Rtsne", "dbscan", "mclust", "RColorBrewer", "viridis", "ggplot2". "scales", "egg", "reshape2"))
After ggplot, period (.) should be replaced by comma(,).

Thanks

**Comment by gabrielakinker** [comment]
Thanks for you message! I am glad you found the code useful. 
I have just fixed the typo.
