### ISSUE TITLE
Request on data preprocessing SCRIPTS in your CCLE_heterogeneity/additional_code / folder 

### ISSUE THREAD

**Issue by howtofindme** [gabrielakinker/CCLE_heterogeneity#4]
Dear Professor Gabriela,

I hope this email finds you well. I am a second-year PhD student at Southeast University in China, where my research focuses on  lung cancer. Your paper on has greatly caught my attention and is highly relevant to my work.

However, I have encountered some difficulties in the preprocessing of the raw data, specifically with the additional_code folder. I believe that there might be some missing scripts for the data processing.

I was wondering if you could provide any insight on how I can obtain these data_processing scripts.
Thank you for your time and consideration.

Best regards,

Young Lee.

**Comment by gabrielakinker** [comment]
Dear Lee,

Additional code for data processing can be found within specific functions like “nmf_programs”.

I hope this helps,
Gabi

**Comment by howtofindme** [comment]
> Dear Lee,
> 
> Additional code for data processing can be found within specific functions like “nmf_programs”.
> 
> I hope this helps, Gabi
Dear Professor Gabriela,
 It is really my honor to hear from you. The problems have been solved under your friendly reminder.
Best,
Yll
